<!DOCTYPE html>
<html>
<head>
    <title>Low Product Quantity Alert</title>
</head>
<body>
    <p>Dear Team,</p>

    <p>I would like to inform you that we have {{ $product->count() }} products low in stock.<br>I have attached the stock report to this email.</p>

    <p>Thanks,<br>E-Commerce Online Dashboard<br><em>This email is auto-generated by the system.</em></p>
</body>
</html>